language: node_js
os:
  - linux
node_js:
  - "8"
sudo: required
addons:
  chrome: stable
before_install:
  - sudo apt-get install npm
  - sudo npm install
  - npm install -g npx
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
  - npm run test
  - npx general-release
